### ISSUE TITLE
Not a bug! Help with understanding the model 'ApiToken'

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [neonexus/sails-react-bootstrap-webpack#60]
Hi,

It would be greatly appreciated if you could explain the usage of the model `ApiToken`. 

I see that there is a route `POST /api/v1/token` has been created. In the policy `isLoggedIn.js`, I see that `ApiToken` model has been used for verification when there is no signed cookie.

But I fail to find where the records for the model `ApiToken` are actually created and what's is its intended purpose. I believe I'm missing something but can't figure out what. Sorry.

Your help would be valuable. Thanks!

**Comment by MaheshkumarSundaram** [comment]
Thanks for the quick response.

>> The controller that the route points to is where they are created.
I understand that it's created in the [controller](https://github.com/neonexus/sails-react-bootstrap-webpack/blob/release/api/controllers/admin/create-api-token.js). But I can't find where the creation is triggered using the route. Currently, I only see them in test coverages.

>> The API tokens are used for, well other APIs to allow them to bypass sessions.
Does the application use them currently? Because when I run the application, I can't see any records being created on the table `apitoken` in DB.

That's why its puzzling for me. Sorry if I sound noobish. Can you clarify a bit on this please?

**Comment by neonexus** [comment]
It's a mechanism I built to help with 3rd party API's connecting to my API; plus, as I said, it's a nice way to test endpoints without having to deal with sessions.

I don't know how else I can possibly tell you about them, other then it's a tool, that if you aren't using, you won't need to use.

**Comment by MaheshkumarSundaram** [comment]
Okay. Thanks
